# https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/
# https://github.com/jkehres/docker-compose-influxdb-grafana
services:
  influxdb:
    image: influxdb:latest
    container_name: "influxdb"
    hostname: "influxdb"
    restart: "unless-stopped"
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=pimonitor
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
  chronograf:
    image: chronograf:latest
    container_name: "chronograf"
    hostname: "chronograf"
    restart: "unless-stopped"
    ports:
      - '127.0.0.1:8888:8888'
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
  grafana:
    image: grafana/grafana:latest
    container_name: "grafana"
    hostname: "grafana"
    restart: "unless-stopped"
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - .docker/grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
volumes:
  influxdb-storage:
  chronograf-storage:
  grafana-storage:
networks:
  default:
    external: true
    name: share-net
