#!/bin/bash
#
# system level cron to run every wednesday at 3 am
# https://www.freeformatter.com/cron-expression-generator-quartz.html
# see https://stackoverflow.com/questions/53151124/jobs-in-etc-cron-d-are-not-working-on-ubuntu
# chown root:root
# chmod 644
#
# Version: 1
MAILTO=""
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

0 8 * * 4 root /mnt/raid/bin/service_backup.sh > /var/log/svc.bak.cron.log 2>&1
