# https://www.jenkins.io/projects/gsoc/2023/project-ideas/docker-compose-build/
# https://hub.docker.com/r/jenkins/jenkins
---
services:
  jenkins:
    image: "jenkins/jenkins:latest-jdk17"
    container_name: "jenkins"
    hostname: "jenkins"
    restart: "unless-stopped"
    privileged: true
    user: "root"
    environment:
      - "JENKINS_OPTS=--httpPort=8080"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "jenkins-home:/var/jenkins_home"
      # sync local TZ and time
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
volumes:
  jenkins-home:
    name: jenkins-home  
networks:
  default:
    external: true
    name: "share-net"
