---
services:
  jenkins:
    image: "jenkins/jenkins:latest-jdk17"
    container_name: "jenkins"
    hostname: "jenkins"
    privileged: true
    user: "root"
    environment:
      - "JENKINS_OPTS=--httpPort=8080"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "jenkins_home:/var/jenkins_home"
volumes:
  jenkins_home: null
networks:
  default:
    external: true
    name: "share-net"
