---
services:
  nexus:
    image: "sonatype/nexus3:latest"
    container_name: "nexus"
    hostname: "nexus"
    volumes:
      - "nexus-data:/nexus-data"
    ports:
      - "8081:8081"
volumes:
  nexus-data: {}
networks:
  default:
    external: true
    name: "share-net"
