# https://hub.docker.com/r/sonatype/nexus3
# https://github.com/sonatype/docker-nexus3/blob/main/docker-compose.yml
---
services:
  nexus:
    image: "sonatype/nexus3:latest"
    container_name: "nexus"
    hostname: "nexus"
    restart: "unless-stopped"
    # attempt to fix container restart issue
    # networks:
    #   default:
    #     ipv4_address: 172.30.0.40
    volumes:
      - "nexus-data:/nexus-data"
      # sync local TZ and time
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8081:8081"
volumes:
  nexus-data:
    name: nexus-data  
networks:
  default:
    external: true
    name: "share-net"
