# https://hub.docker.com/_/sonarqube
# https://github.com/SonarSource/docker-sonarqube/blob/master/example-compose-files/sq-with-postgres/docker-compose.yml
---
services:
  sonarqube:
    image: "sonarqube:9.9.8-community"
    hostname: "sonarqube"
    container_name: "sonarqube"
    restart: "unless-stopped"
    depends_on:
      - "db"
    entrypoint:
      - /bin/sh
      - /map-env.sh
      - SONAR_JDBC_PASSWORD=SONAR_DB_PASSWORD
      - --
    command: ["/opt/sonarqube/docker/entrypoint.sh"]
    environment:
      SONAR_JDBC_URL: "jdbc:postgresql://db:5432/sonar"
      SONAR_JDBC_USERNAME: "sonar"
    volumes:
      - "sonarqube-data:/opt/sonarqube/data"
      - "sonarqube-extensions:/opt/sonarqube/extensions"
      - "./log:/opt/sonarqube/logs"
      - /etc/environment:/etc/host-environment:ro
      - ./_common/map-env.sh:/map-env.sh:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: host
    labels:
      - 'diun.include_tags=^\d+\.\d+\.\d+-community$$'
      - traefik.enable=true
      - traefik.http.routers.sonarqube.rule=Host(`sonarqube.tecronin.uk`)
      - traefik.http.routers.sonarqube.entrypoints=websecure
      - traefik.http.services.sonarqube.loadbalancer.server.port=9000
  db:
    image: "postgres:13.23"
    hostname: "postgresql"
    container_name: "postgresql"
    restart: "unless-stopped"
    entrypoint:
      - /bin/sh
      - /map-env.sh
      - POSTGRES_PASSWORD=SONAR_DB_PASSWORD
      - --
    command: ["docker-entrypoint.sh", "postgres"]
    environment:
      POSTGRES_USER: "sonar"
      POSTGRES_DB: "sonar"
    volumes:
      - "postgresql:/var/lib/postgresql"
      - "postgresql-data:/var/lib/postgresql/data"
      # sync local TZ and time
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/environment:/etc/host-environment:ro
      - ./_common/map-env.sh:/map-env.sh:ro
volumes:
  sonarqube-data:
    name: sonarqube-data
  sonarqube-extensions:
    name: sonarqube-extensions
  sonarqube-logs:
    name: sonarqube-logs
  postgresql:
    name: postgresql
  postgresql-data:
    name: postgresql-data
networks:
  default:
    external: true
    name: "share-net"
