version: "3.7"
services:
  # https://hub.docker.com/r/jacobalberty/unifi
  # https://github.com/jacobalberty/unifi-docker 
  unifi:
    image: jacobalberty/unifi:v7.2.92
    container_name: "unifi"
    restart: always
    volumes:
      - ./unifi:/unifi
    ports:
      - 3478:3478/udp # STUN
      - 10001:10001/udp # AP discovery
      - 8882:8882/tcp # Device/ controller comm.
      - 8443:8443/tcp # Controller GUI/API as seen in a web browser
    environment:
      - UNIFI_HTTP_PORT=8882
      - TZ=America/Chicago
networks:
  default:
    external: true
    name: share-net
