---
services:
  unifi:
    image: jacobalberty/unifi:v8.6.9
    container_name: "unifi"
    restart: "always"
    volumes:
      - "./unifi:/unifi"
      - "./cert:/unifi/cert"
    ports:
      - "3478:3478/udp"
      - "10001:10001/udp"
      - "8882:8882/tcp"
      - "443:443/tcp"
    environment:
      - "UNIFI_HTTP_PORT=8882"
      - "UNIFI_HTTPS_PORT=443"
      - "TZ=America/Chicago"
networks:
  default:
    external: true
    name: "share-net"
