version: "3.7"
services:
  # https://hub.docker.com/r/jacobalberty/unifi
  # https://github.com/jacobalberty/unifi-docker 
  unifi:
    image: jacobalberty/unifi:v8.3
    container_name: "unifi"
    restart: always
    volumes:
      - ./unifi:/unifi
      # need to provide ssl cert, private key, and CA cert as chain file
      # https://github.com/jacobalberty/unifi-docker#certificate-support
      - ./cert:/unifi/cert
    ports:
      - 3478:3478/udp # STUN
      - 10001:10001/udp # AP discovery
      - 8882:8882/tcp # Device/ controller comm.
      - 443:443/tcp # Controller GUI/API as seen in a web browser
    environment:
      - UNIFI_HTTP_PORT=8882
      - UNIFI_HTTPS_PORT=443
      - TZ=America/Chicago
networks:
  default:
    external: true
    name: share-net
