# https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/
# https://github.com/jkehres/docker-compose-influxdb-grafana
# https://ivanahuckova.medium.com/setting-up-influxdb-v2-flux-with-influxql-in-grafana-926599a19eeb
# https://hub.docker.com/_/influxdb
# https://hub.docker.com/r/grafana/grafana
# https://observability-360.com/docs/ViewDocument?id=influxdb-and-grafana
services:
  influxdb:
    image: influxdb:2.7.11
    container_name: "influxdb"
    hostname: "influxdb"
    restart: "unless-stopped"
    ports:
      - '8086:8086'
    volumes:
      - influxdb-data:/var/lib/influxdb
      - influxdb-data2:/var/lib/influxdb2
      - influxdb-conf:/etc/influxdb2
      # sync local TZ and time
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - INFLUXDB_DB=pimonitor
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
  grafana:
    image: grafana/grafana:11.6.1
    container_name: "grafana"
    hostname: "grafana"
    restart: "unless-stopped"
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-provisioning:/etc/grafana/provisioning
      # sync local TZ and time
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_SECURITY_CSRF_TRUSTED_ORIGINS=${GRAFANA_DOMAIN}
volumes:
  influxdb-data:
    name: influxdb-data
  influxdb-data2:
    name: influxdb-data2
  influxdb-conf:
    name: influxdb-conf
  grafana-data:
    name: grafana-data
  grafana-provisioning:
    name: grafana-provisioning
networks:
  default:
    external: true
    name: share-net
