---
services:
  restorer:
    image: ubuntu:22.04
    container_name: restorer
    hostname: restorer
    tty: true
    volumes:
      - restorer:/restorer:rw
      - backup:/backup:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - diun.enable=false
volumes:
  restorer:
    name: restorer
