# https://hub.docker.com/_/sonarqube
# https://github.com/SonarSource/docker-sonarqube/blob/master/example-compose-files/sq-with-postgres/docker-compose.yml
---
services:
  sonarqube:
    image: "sonarqube:lts-community"
    hostname: "sonarqube"
    container_name: "sonarqube"
    restart: "unless-stopped"
    depends_on:
      - "db"
    environment:
      SONAR_JDBC_URL: "jdbc:postgresql://db:5432/sonar"
      SONAR_JDBC_USERNAME: "sonar"
      SONAR_JDBC_PASSWORD: "sonar"
    volumes:
      - "sonarqube-data:/opt/sonarqube/data"
      - "sonarqube-extensions:/opt/sonarqube/extensions"
      - "./log:/opt/sonarqube/logs"
      # sync local TZ and time
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: host    
  db:
    image: "postgres:13"
    hostname: "postgresql"
    container_name: "postgresql"
    restart: "unless-stopped"
    environment:
      POSTGRES_USER: "sonar"
      POSTGRES_PASSWORD: "sonar"
      POSTGRES_DB: "sonar"
    volumes:
      - "postgresql:/var/lib/postgresql"
      - "postgresql-data:/var/lib/postgresql/data"
      # sync local TZ and time
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host    
volumes:
  sonarqube-data:
    name: sonarqube-data
  sonarqube-extensions:
    name: sonarqube-extensions
  sonarqube-logs:
    name: sonarqube-logs
  postgresql:
    name: postgresql
  postgresql-data:
    name: postgresql-data
networks:
  default:
    external: true
    name: "share-net"
