# https://hub.docker.com/_/sonarqube
# https://github.com/SonarSource/docker-sonarqube/blob/master/example-compose-files/sq-with-postgres/docker-compose.yml
---
services:
  sonarqube:
    image: "sonarqube:community"
    hostname: "sonarqube"
    container_name: "sonarqube"
    restart: "unless-stopped"
    depends_on:
      - "db"
    environment:
      SONAR_JDBC_URL: "jdbc:postgresql://db:5432/sonar"
      SONAR_JDBC_USERNAME: "sonar"
      SONAR_JDBC_PASSWORD: "sonar"
    volumes:
      - "sonarqube-data:/opt/sonarqube/data"
      - "sonarqube-extensions:/opt/sonarqube/extensions"
      - "sonarqube-logs:/opt/sonarqube/logs"
      # sync local TZ and time
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9000:9000"
  db:
    image: "postgres:13"
    hostname: "postgresql"
    container_name: "postgresql"
    restart: "unless-stopped"
    environment:
      POSTGRES_USER: "sonar"
      POSTGRES_PASSWORD: "sonar"
      POSTGRES_DB: "sonar"
    volumes:
      - "postgresql:/var/lib/postgresql"
      - "postgresql-data:/var/lib/postgresql/data"
      # sync local TZ and time
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5432:5432"
volumes:
  sonarqube-data:
    name: sonarqube-data
  sonarqube-extensions:
    name: sonarqube-extensions
  sonarqube-logs:
    name: sonarqube-logs
  postgresql:
    name: postgresql
  postgresql-data:
    name: postgresql-data
networks:
  default:
    external: true
    name: "share-net"
