services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    # hostname needed or it rebuilds data every restart
    hostname: "rabbitmq"
    restart: unless-stopped
    command: sh -c "rabbitmq-plugins enable rabbitmq_mqtt && rabbitmq-server"
    ports:
      - "5672:5672"
      - "15672:15672"
      - "1883:1883"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./.sbin:/root/bin
      - ./mqtt.conf:/etc/rabbitmq/conf.d/20-mqtt.conf:ro
    
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  rabbitmq_data:
    name: rabbitmq_data

networks:
  default:
    external: true
    name: share-net
