---
services:
  nginx:
    image: "nginx:stable-alpine-slim"
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./log:/var/log/nginx"
networks:
  default:
    external: true
    name: "share-net"
