version: "3.7"
services:
  # https://hub.docker.com/_/nginx
  # https://github.com/nginxinc/docker-nginx
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./log:/var/log/nginx
networks:
  default:
    external: true
    name: share-net
