# https://hub.docker.com/_/nginx
# https://github.com/linuxserver/docker-nginx
# TODO https://github.com/NginxProxyManager/nginx-proxy-manager
---
services:
  nginx:
    image: "nginx:stable-alpine-slim"
    container_name: "nginx"
    hostname: "nginx"
    restart: "unless-stopped"
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./log:/var/log/nginx"
networks:
  default:
    external: true
    name: "share-net"
