# https://hub.docker.com/r/openhab/openhab
# https://www.openhab.org/docs/
---
services:
  openhab:
    image: "openhab/openhab:latest-alpine"
    container_name: "openhab"
    hostname: "openhab"
    restart: "unless-stopped"
    ports:
      - "8881:8881"
    volumes:
      - "openhab-addons:/openhab/addons"
      - "openhab-conf:/openhab/conf"
      - "openhab-userdata:/openhab/userdata"
      # sync local TZ and time
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    devices:
      # TODO move to envar
      - "/dev/ttyACM0:/dev/ttyACM0"
    environment:
      # TODO move to envar
      OPENHAB_HTTP_PORT: 8881
      OPENHAB_HTTPS_PORT: 8543
      EXTRA_JAVA_OPTS: "-Duser.timezone=America/Chicago -Dgnu.io.rxtx.SerialPorts==/dev/ttyACM0"
      USER_ID: 9001
      GROUP_ID: 9001
volumes:
  openhab-addons:
    name: openhab-addons  
  openhab-conf:
    name: openhab-conf  
  openhab-userdata:
    name: openhab-userdata  
networks:
  default:
    external: true
    name: "share-net"
